import * as fs from 'fs'
import * as path from 'path'
import { barrel_generator } from './barrel_generator-sidecar'
import { barrel_scanning } from './barrel_scanning-sidecar'

const SIDE_CAR_EXTENSION = 'ts'
const GENERATED_FILE_HEADER = [
  '/* eslint-disable */',
  '/* tslint:disable */',
  '// THIS FILE IS AuTo-GeNeRaTeD BY barrel-rider-sidecar. DO NOT EDIT',
  '// see: https://www.npmjs.com/package/barrel-rider-sidecar',
].join('\n')

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

function shouldDeleteForSource(filePath: string): boolean {
  if (isGeneratedSidecarFile(filePath)) {
    return true
  }

  if (filePath.endsWith('.d.ts')) {
    return true
  }

  return (
    filePath.includes('.spec.') ||
    filePath.includes('.test.') ||
    filePath.includes('.e2e.')
  )
}

export function isGeneratedSidecarFile(filePath: string): boolean {
  return (
    /-sidecar\.(ts|tsx)$/.test(filePath) ||
    /\.sidecar\.(ts|tsx)$/.test(filePath)
  )
}

export function getSidecarFilename(filePath: string): string {
  const extension = path.extname(filePath)
  const pathWithoutExtension = filePath.slice(
    0,
    filePath.length - extension.length,
  )
  return `${pathWithoutExtension}-sidecar.${SIDE_CAR_EXTENSION}`
}

function getExportName(filePath: string): string {
  const basename = path.basename(filePath)
  const lastDot = basename.lastIndexOf('.')
  const filename = basename.substring(0, lastDot)
  return filename.replace(/\./g, '_')
}

function shouldSkipManagedFile(contents: string | null): boolean {
  console.log('checking for ignore directives in existing sidecar file')

  if (!contents) {
    return false
  }

  let beginning = contents.substring(0, 200).trimStart()

  console.log(beginning)

  return (
    beginning.includes('barrel-rider:ignore') ||
    beginning.includes('sidecar:ignore')
  )
}

function hasNamedExport(
  filePath: string,
  exportName: string,
  fileContents: string,
): boolean {
  if (exportName.includes('index')) {
    return false
  }

  const directExportPattern = new RegExp(
    `\\s*export\\s+(async\\s+)?(const|function|interface|type|class)\\s+(${escapeRegExp(
      exportName,
    )})(\\s|\\()`,
  )
  const reExportPattern = new RegExp(
    `\\s*export\\s+{.*(\\s+|\\,)(${escapeRegExp(exportName)})(\\s+|\\,|\\})`,
  )

  return (
    directExportPattern.test(fileContents) || reExportPattern.test(fileContents)
  )
}

export type SidecarGeneration = {
  sidecarFilename: string
  contents: string | null
}

export function createSidecarGeneration(
  filePath: string,
  verbose: boolean,
): SidecarGeneration {
  const sidecarFilename = getSidecarFilename(filePath)
  if (shouldDeleteForSource(filePath)) {
    return {
      sidecarFilename,
      contents: null,
    }
  }

  const extension = path.extname(filePath)
  const filename = path.basename(filePath, extension)

  const currentFileContents = barrel_scanning.readFileIfPresent(filePath) || ''

  if (!currentFileContents.trim()) {
    return {
      sidecarFilename,
      contents: null,
    }
  }

  const exportName = getExportName(filePath)
  if (shouldSkipManagedFile(currentFileContents)) {
    if (verbose) {
      console.log(
        'skipping sidecar generation for',
        filePath,
        'because of ignore directive',
      )
    }
    return {
      sidecarFilename,
      contents: null,
    }
  }

  if (hasNamedExport(filePath, exportName, currentFileContents)) {
    return {
      sidecarFilename,
      contents: null,
    }
  }

  return {
    sidecarFilename,
    contents: [
      GENERATED_FILE_HEADER,
      `import * as ${exportName} from './${filename}'`,
      `export { ${exportName} }`,
    ].join('\n'),
  }
}
